version: '3'
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT:-10}"

  confgend:
    image: wazoplatform/wazo-confgend-test:local
    entrypoint: ["wazo-confgend"]
    # ports:
    #   - "8669"
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      # for live code update
      - "${CONFGEND_SRC:-../../..}:/usr/local/src/wazo-confgend"
      # for reference data
      - "${DATA_DIR:-./data}:/data"
      - "./etc/wazo-confgend/conf.d:/etc/wazo-confgend/conf.d"
      # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/opt/venv/lib/python2.7/site-packages/xivo_dao"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python2.7/site-packages/xivo"

  postgres:
    image: wazoplatform/wazo-confgend-db-test:local
    ports:
      - "5432"
